# Generated by Django 2.2 on 2020-10-16 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20201015_0522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='list_item',
            new_name='name',
        ),
        migrations.AddField(
            model_name='list',
            name='template',
            field=models.CharField(default='home.html', max_length=200),
        ),
    ]
