# Generated by Django 2.2 on 2020-10-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_auto_20201016_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('text', models.TextField(default="This is a bad mad lib because it isn't one.")),
                ('word_type', models.CharField(choices=[('noun', 'noun'), ('plural_noun', 'plural noun'), ('body_part', 'body part'), ('accessory', 'accessory'), ('clothing', 'clothing item'), ('location', 'location'), ('feeling', 'feeling'), ('car', 'car type or name'), ('spice', 'spice'), ('month', 'month'), ('day_time', 'time of the day'), ('unit_measurement', 'unit of measurement'), ('temperature', 'temperature'), ('exclamation', 'exclamation'), ('time', 'unit of time'), ('nickname', 'nickname'), ('number', 'number'), ('large_num', 'large number'), ('name', 'name'), ('famous', "famous person's name"), ('adjective', 'adjective'), ('adverb', 'adverb'), ('verb', 'verb'), ('ing_verb', "verb ending in 'ing' ")], default='0', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='list',
            name='template',
            field=models.CharField(default='home', max_length=200),
        ),
    ]
