# Generated by Django 2.2 on 2020-10-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_auto_20201016_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lib',
            name='accessory',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='lib',
            name='adjective',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='lib',
            name='adverb',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='lib',
            name='body_part',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='lib',
            name='car_name_or_type',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='lib',
            name='clothing_item',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='lib',
            name='exclamation',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='lib',
            name='feeling',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='lib',
            name='large_number',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='lib',
            name='location',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='lib',
            name='name_of_famous_person',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='lib',
            name='nickname',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='lib',
            name='noun',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='lib',
            name='number',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='lib',
            name='plural_noun',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='lib',
            name='spice',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='lib',
            name='temperature',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='lib',
            name='time_of_day',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='lib',
            name='unit_of_measurement',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='lib',
            name='unit_of_time',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='lib',
            name='verb',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='lib',
            name='verb_ending_in_ing',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
