# Generated by Django 2.2 on 2020-10-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_auto_20201016_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lib',
            name='noun',
            field=models.IntegerField(default=0),
        ),
    ]
