# Generated by Django 2.2 on 2020-10-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0010_auto_20201016_0710'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
