# Generated by Django 2.2 on 2020-10-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0011_formelements'),
    ]

    operations = [
        migrations.AddField(
            model_name='formelements',
            name='nouns',
            field=models.CharField(default='home', max_length=1000),
        ),
    ]
