# Generated by Django 2.2 on 2020-10-18 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0012_formelements_nouns'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormElements',
        ),
    ]
