# Generated by Django 2.2 on 2020-10-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0013_delete_formelements'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('noun', models.CharField(max_length=200)),
                ('plural_noun', models.CharField(max_length=200)),
                ('body_part', models.CharField(max_length=200)),
                ('accessory', models.CharField(max_length=200)),
                ('clothing_item', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('feeling', models.CharField(max_length=200)),
                ('car_name_or_type', models.CharField(max_length=200)),
                ('spice', models.CharField(max_length=200)),
                ('time_of_day', models.CharField(max_length=200)),
                ('unit_of_measurement', models.CharField(max_length=200)),
                ('temperature', models.CharField(max_length=200)),
                ('exclamation', models.CharField(max_length=200)),
                ('unit_of_time', models.CharField(max_length=200)),
                ('nickname', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200)),
                ('large_number', models.CharField(max_length=200)),
                ('name_of_famous_person', models.CharField(max_length=200)),
                ('adjective', models.CharField(max_length=200)),
                ('adverb', models.CharField(max_length=200)),
                ('verb', models.CharField(max_length=200)),
                ('verb_ending_in_ing', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
