# Generated by Django 2.2 on 2020-10-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0014_auto_20201019_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='formelement',
            name='type',
            field=models.CharField(default='bacon', max_length=200),
            preserve_default=False,
        ),
    ]
