# Generated by Django 2.2 on 2020-10-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0015_formelement_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formelement',
            name='accessory',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='adjective',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='adverb',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='body_part',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='car_name_or_type',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='clothing_item',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='exclamation',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='feeling',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='large_number',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='location',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='name',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='name_of_famous_person',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='noun',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='number',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='plural_noun',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='spice',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='time_of_day',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='type',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='unit_of_measurement',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='unit_of_time',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='verb',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='verb_ending_in_ing',
        ),
        migrations.AddField(
            model_name='formelement',
            name='type1',
            field=models.CharField(default='bacon', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formelement',
            name='type10',
            field=models.CharField(default='bacon', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formelement',
            name='type2',
            field=models.CharField(default='bacon', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formelement',
            name='type3',
            field=models.CharField(default='bacon', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formelement',
            name='type4',
            field=models.CharField(default='bacon', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formelement',
            name='type5',
            field=models.CharField(default='bacon', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formelement',
            name='type6',
            field=models.CharField(default='bacob', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formelement',
            name='type7',
            field=models.CharField(default='bacon', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formelement',
            name='type8',
            field=models.CharField(default='bacon', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formelement',
            name='type9',
            field=models.CharField(default='bacon', max_length=100),
            preserve_default=False,
        ),
    ]
