# Generated by Django 2.2 on 2020-10-20 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0017_auto_20201020_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formelement',
            name='type10',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='type2',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='type3',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='type4',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='type5',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='type6',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='type7',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='type8',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='type9',
        ),
    ]
