# Generated by Django 2.2 on 2020-10-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0018_auto_20201020_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='formelement',
            name='type10',
            field=models.CharField(default='bacon', max_length=100),
        ),
        migrations.AddField(
            model_name='formelement',
            name='type2',
            field=models.CharField(default='bacon', max_length=100),
        ),
        migrations.AddField(
            model_name='formelement',
            name='type3',
            field=models.CharField(default='bacon', max_length=100),
        ),
        migrations.AddField(
            model_name='formelement',
            name='type4',
            field=models.CharField(default='bacon', max_length=100),
        ),
        migrations.AddField(
            model_name='formelement',
            name='type5',
            field=models.CharField(default='bacon', max_length=100),
        ),
        migrations.AddField(
            model_name='formelement',
            name='type6',
            field=models.CharField(default='bacon', max_length=100),
        ),
        migrations.AddField(
            model_name='formelement',
            name='type7',
            field=models.CharField(default='bacon', max_length=100),
        ),
        migrations.AddField(
            model_name='formelement',
            name='type8',
            field=models.CharField(default='bacon', max_length=100),
        ),
        migrations.AddField(
            model_name='formelement',
            name='type9',
            field=models.CharField(default='bacon', max_length=100),
        ),
    ]
