# Generated by Django 2.2 on 2020-10-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0019_auto_20201020_0305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formelement',
            name='type',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='type10',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='type2',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='type3',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='type4',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='type5',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='type6',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='type7',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='type8',
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='type9',
        ),
        migrations.AddField(
            model_name='formelement',
            name='accessory',
            field=models.CharField(default='glasses', max_length=200),
        ),
        migrations.AddField(
            model_name='formelement',
            name='adjective',
            field=models.CharField(default='ugly', max_length=200),
        ),
        migrations.AddField(
            model_name='formelement',
            name='adverb',
            field=models.CharField(default='gently', max_length=200),
        ),
        migrations.AddField(
            model_name='formelement',
            name='body_part',
            field=models.CharField(default='ear', max_length=200),
        ),
        migrations.AddField(
            model_name='formelement',
            name='car_name_or_type',
            field=models.CharField(default='tesla', max_length=200),
        ),
        migrations.AddField(
            model_name='formelement',
            name='clothing_item',
            field=models.CharField(default='sock', max_length=200),
        ),
        migrations.AddField(
            model_name='formelement',
            name='exclamation',
            field=models.CharField(default='ah rats.', max_length=200),
        ),
        migrations.AddField(
            model_name='formelement',
            name='feeling',
            field=models.CharField(default='happy', max_length=200),
        ),
        migrations.AddField(
            model_name='formelement',
            name='large_number',
            field=models.CharField(default='1002', max_length=200),
        ),
        migrations.AddField(
            model_name='formelement',
            name='location',
            field=models.CharField(default='park', max_length=200),
        ),
        migrations.AddField(
            model_name='formelement',
            name='name',
            field=models.CharField(default='madlib name', max_length=500),
        ),
        migrations.AddField(
            model_name='formelement',
            name='name_of_famous_person',
            field=models.CharField(default='King George', max_length=200),
        ),
        migrations.AddField(
            model_name='formelement',
            name='nickname',
            field=models.CharField(default='honey', max_length=200),
        ),
        migrations.AddField(
            model_name='formelement',
            name='noun',
            field=models.CharField(default='banana', max_length=200),
        ),
        migrations.AddField(
            model_name='formelement',
            name='number',
            field=models.CharField(default='90', max_length=200),
        ),
        migrations.AddField(
            model_name='formelement',
            name='plural_noun',
            field=models.CharField(default='monkeys', max_length=200),
        ),
        migrations.AddField(
            model_name='formelement',
            name='spice',
            field=models.CharField(default='salt', max_length=200),
        ),
        migrations.AddField(
            model_name='formelement',
            name='temperature',
            field=models.CharField(default='79', max_length=200),
        ),
        migrations.AddField(
            model_name='formelement',
            name='time_of_day',
            field=models.CharField(default='evening', max_length=200),
        ),
        migrations.AddField(
            model_name='formelement',
            name='unit_of_measurement',
            field=models.CharField(default='cup', max_length=200),
        ),
        migrations.AddField(
            model_name='formelement',
            name='unit_of_time',
            field=models.CharField(default='seconds', max_length=200),
        ),
        migrations.AddField(
            model_name='formelement',
            name='verb',
            field=models.CharField(default='run', max_length=200),
        ),
        migrations.AddField(
            model_name='formelement',
            name='verb_ending_in_ing',
            field=models.CharField(default='swimming', max_length=200),
        ),
    ]
