# Generated by Django 2.2 on 2020-10-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0020_auto_20201020_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrickElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='brick', max_length=500)),
                ('noun', models.CharField(default='', max_length=200)),
                ('plural_noun', models.CharField(default='', max_length=200)),
                ('adjective', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='FormElement',
        ),
    ]
