# Generated by Django 2.2 on 2020-10-20 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0021_auto_20201020_0417'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BrickElements',
            new_name='BrickElement',
        ),
    ]
