# Generated by Django 2.2 on 2020-10-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0022_auto_20201020_0439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brickelement',
            old_name='name',
            new_name='field1',
        ),
        migrations.RenameField(
            model_name='brickelement',
            old_name='adjective',
            new_name='field2',
        ),
        migrations.RenameField(
            model_name='brickelement',
            old_name='noun',
            new_name='field3',
        ),
        migrations.RenameField(
            model_name='brickelement',
            old_name='plural_noun',
            new_name='field4',
        ),
        migrations.AddField(
            model_name='brickelement',
            name='field5',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='brickelement',
            name='field6',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='brickelement',
            name='field7',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='brickelement',
            name='field8',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='brickelement',
            name='field9',
            field=models.CharField(default='', max_length=200),
        ),
    ]
