# Generated by Django 2.2 on 2020-10-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0023_auto_20201020_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='brickelement',
            name='name',
            field=models.CharField(default='Bricks', max_length=100),
        ),
        migrations.AlterField(
            model_name='brickelement',
            name='field1',
            field=models.CharField(default='', max_length=500),
        ),
    ]
