# Generated by Django 2.2 on 2020-10-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0030_quoteelement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poem1Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Love Poem #1', max_length=100)),
                ('field1', models.CharField(default='', max_length=500)),
                ('field2', models.CharField(default='', max_length=200)),
                ('field3', models.CharField(default='', max_length=200)),
                ('field4', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
