# Generated by Django 2.2 on 2020-10-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0031_poem1element'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poem3Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='How Do I Love Thee?', max_length=100)),
                ('field1', models.CharField(default='', max_length=500)),
                ('field2', models.CharField(default='', max_length=200)),
                ('field3', models.CharField(default='', max_length=200)),
                ('field4', models.CharField(default='', max_length=200)),
                ('field5', models.CharField(default='', max_length=200)),
                ('field6', models.CharField(default='', max_length=200)),
                ('field7', models.CharField(default='', max_length=200)),
                ('field8', models.CharField(default='', max_length=200)),
                ('field9', models.CharField(default='', max_length=200)),
                ('field10', models.CharField(default='', max_length=200)),
                ('field11', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='poem1element',
            name='name',
            field=models.CharField(default='Love Poem', max_length=100),
        ),
    ]
