# Generated by Django 2.2 on 2020-10-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0032_auto_20201020_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='A Mad Lib Story', max_length=100)),
                ('field1', models.CharField(default='', max_length=500)),
                ('field2', models.CharField(default='', max_length=200)),
                ('field3', models.CharField(default='', max_length=200)),
                ('field4', models.CharField(default='', max_length=200)),
                ('field5', models.CharField(default='', max_length=200)),
                ('field6', models.CharField(default='', max_length=200)),
                ('field7', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
